import numpy as np
import igl
# Bindings using C++ and Eigen:
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../build/')))
from gpytoolbox_eigen_bindings import upper_envelope

def upper_envelope_fixed(v,t,d):
    # This is a **TEMPORARY** function that flips the bad tets generated by upper_envelope. This function will be removed when upper_enveloped is fixed.
    u, g, l = upper_envelope(v,t,d)
    bad_tets = igl.volume(u,g)<0
    g_bad_tets = g[bad_tets,:]
    g_bad_tets = g_bad_tets[:,[1,0,2,3]]
    g[bad_tets,:] = g_bad_tets
    return u,g,l