name: Full build (Linux)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v3
        with:
          name: libigl/libigl
          submodules: 'recursive'

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install \
              libmpfr-dev \
              libgmp-dev \

      - name: Build libigl
        shell: bash -l {0}
        run: |
          mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && 
          cmake --build "." --config Release

# see https://github.com/libigl/libigl/blob/main/.github/workflows/continuous.yml