name: Full build (Windows)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "windows-latest"
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     auto-update-conda: true
      #     python-version: "3.7"

      - name: Install dependencies (Windows)
        shell: bash -l {0}
        run: |
          python -m pip install "numpy<=1.96.0"
          python -m pip install scipy
          python -m pip install scikit-image

      # - name: Install dependencies (Windows)
      #   shell: bash -l {0}
      #   run: |
      #     conda info
      #     conda install numpy
      #     conda install scipy=1.6.1
        # conda install -c conda-forge igl
        # conda install -c conda-forge matplotlib 
        # python -m pip install --upgrade pip
        # python -m pip install polyscope
        # python -m pip install tetgen
        # python -m pip install scikit-image
        # conda install -c conda-forge cython
        # conda install -c conda-forge suitesparse
        # pip install git+https://github.com/EmJay276/scikit-sparse
        # conda install scipy=1.6.1

      - name: Install c++ bindings
        shell: bash -l {0}
        run: |
          mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && 
          cmake --build "." --config Release

      # - name: Debug
      #   shell: bash -l {0}
      #   run: |
      #     cd D:
      #     ls
      #     cd a
      #     ls

      - name: copying dlls
        shell: bash -l {0}
        run: |
          cp .\\build\\_deps\\gmp-src\\lib\\libgmp-10.dll .\\build\\.
          cp .\\build\\_deps\\mpfr-src\\lib\\libmpfr-4.dll .\\build\\.
          cp .\\build\\_deps\\gmp-src\\lib\\libgmp-10.dll .\\build\\Release\\.
          cp .\\build\\_deps\\mpfr-src\\lib\\libmpfr-4.dll .\\build\\Release\\.
          cp .\\build\\_deps\\gmp-src\\lib\\libgmp-10.dll .
          cp .\\build\\_deps\\mpfr-src\\lib\\libmpfr-4.dll .

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          python -m pip install tetgen
          python -m unittest -v
        # python -c "import gpytoolbox"
        # python -c "import gpytoolbox_bindings"
          
        # python -m unittest -v

# see https://github.com/libigl/libigl/blob/main/.github/workflows/continuous.yml
